### ISSUE TITLE
when passing url parameters, the virtual route doesn't work

### ISSUE THREAD

**Issue by zoranpopovic** [WindsonFF/vite-plugin-virtual-html#2]
something like localhost:3000/foo.html?test=test seems to break this plugin.  quick look at the code, shows that it looks for .endsWith(".html") etc, which naturally doesn't work with parameters....

**Comment by WindsonFF** [comment]
i've fixed this issue , could you try again later?

**Comment by zoranpopovic** [comment]
yes, it works, that was quick !

**Comment by WindsonFF** [comment]
😋
