### ISSUE TITLE
page is not exists,please check your pages or indexPage configuration 

### ISSUE THREAD

**Issue by pasBone** [WindsonFF/vite-plugin-virtual-html#4]
https://github.com/WindsonFF/vite-plugin-virtual-html/blob/7308558d3ded2d1c0156fd3e3fc61f8ca1c680d0/src/index.ts#L46

page is not exists,please check your pages or indexPage configuration，

使用中文路径的时候会报这个错误，是否需要在 req.url 处添加一个 decodeURI 呢。

**Comment by WindsonFF** [comment]
我测试没有出现这个问题...请提供一个简单的示例

i test it with Chinese character and it had no such error message.

**Comment by WindsonFF** [comment]
这是我测试用的配置: 
```
const pages = {
  demo2: '/页面/demo2/demo2.html',
}
export default defineConfig({
  resolve:{
    alias: {
      'vue': 'vue/dist/vue.esm-bundler.js'
    }
  },
  plugins: [
    Vue(),
    VirtualHtml({
      pages,
      indexPage: 'demo2',
    }),
  ],
})
```
