### ISSUE TITLE
使用这个插件之后不能hot reload

### ISSUE THREAD

**Issue by pasBone** [WindsonFF/vite-plugin-virtual-html#6]
使用这个插件之后不能hot reload, 注释掉插件就可以

**Comment by WindsonFF** [comment]
代码中的示例测试是可以的.

**Comment by pasBone** [comment]
我刚刚下载了您的demo测试了下。修改vue文件是可以 reload的。 但是修改 .html 里面的内容没有反应，因为我这边是有很多的.html文件，修改频率也非常高，所以才关注到了这一点。

**Comment by pasBone** [comment]
但是注释掉这个插件之后，再访问根目录下的 index.html 是可以热更新的

**Comment by WindsonFF** [comment]
你是不是配置了`indexPage`嘛.

**Comment by pasBone** [comment]
我试了下无论配置不配置indexPage, html都没有热更新呀

**Comment by WindsonFF** [comment]
你是咋配置的?

**Comment by pasBone** [comment]
可能是被我魔改改坏了 。。。我把issue关了哈，谢谢
